<a href="https://colab.research.google.com/github/HarikaPonnaganti-coder/Machine-Learning/blob/main/AP24110010828_NumPy_HandsOn_Array_to_Image_Analysis_Student_Lab_v2_(7).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Hands-on Lab: From Arrays to Image Analysis

## Student Practice Notebook

**Name:** P.Harika
**Register Number:** AP24110010828
**Date:** 15/06/26

## Learning Objectives

After completing this lab, you will be able to:

- Create and manipulate NumPy arrays
- Understand array properties and dimensions
- Perform indexing and slicing
- Apply mathematical operations
- Understand and explain broadcasting
- Analyze images using NumPy arrays
- Perform basic image transformations
- Explain *why* NumPy is used in real ML/Data Science pipelines, not just *how*

### How to use this notebook
- **Demonstration** cells: run them, read the output, understand it.
- **Practice** cells: write your own code — don't copy the demo verbatim.
- **Predict-then-run**: before running some cells, you'll be asked to *predict* the output first. Write your prediction in the markdown cell, then run and compare.
- **Reflection**: short written answers, in your own words.


## Part 1: Introduction to NumPy

NumPy (Numerical Python) is a Python library used for efficient numerical computation.

**Why not just use Python lists?** Python lists store objects with overhead per element and loop in pure Python. NumPy arrays store raw numbers in contiguous memory and use compiled C code for operations — this is called **vectorization**. That's why NumPy is used everywhere in:

- Data Science (pandas is built on NumPy)
- Machine Learning (feeding data into models as arrays/tensors)
- Image Processing (an image *is* a NumPy array)
- Scientific Computing

Let's actually *see* the speed difference before we take it on faith.


In [1]:
import numpy as np
import matplotlib.pyplot as plt

print("NumPy is ready!")


NumPy is ready!


### Demonstration: Loops vs. Vectorization (the "why" behind NumPy)

Below we add 1 to a million numbers two ways: a plain Python loop, and a NumPy array operation.
Run this cell and look at the timing output.


In [2]:
import time

n = 1_000_000
python_list = list(range(n))
numpy_array = np.arange(n)

start = time.time()
result_list = [x + 1 for x in python_list]
loop_time = time.time() - start

start = time.time()
result_array = numpy_array + 1
vector_time = time.time() - start

print(f"Python loop time : {loop_time:.5f} seconds")
print(f"NumPy vector time: {vector_time:.5f} seconds")
print(f"NumPy was about {loop_time/vector_time:.0f}x faster")


Python loop time : 0.05587 seconds
NumPy vector time: 0.00320 seconds
NumPy was about 17x faster


**Reflection (write your answer):** Based on the timing above, in your own words, why is NumPy faster than a Python loop for this kind of operation? #AP24110010828

*Your answer:*NumPy is faster because its array operations are vectorized and implemented using optimized compiled code. Instead of Python processing every element one by one, NumPy can perform the operation on the entire array efficiently. NumPy arrays also store numerical data more efficiently than normal Python lists. #AP24110010828


## Part 2: Creating NumPy Arrays

### Demonstration

In [3]:
arr = np.array([10,20,30,40,50])
arr


array([10, 20, 30, 40, 50])

### Student Practice

Create an array containing:

5, 10, 15, 20, 25

Write your code below (do not just copy the demo — change the numbers yourself):


In [4]:
# Import the NumPy library.
# "np" is the short name (alias) we will use for NumPy.
import numpy as np                        #AP24110010828

# Create a NumPy array containing the required numbers.
arr = np.array([5, 10, 15, 20, 25])       #AP24110010828

# Display the array.                      #AP24110010828
print(arr)


[ 5 10 15 20 25]


## Part 3: Array Properties

Important properties:

- `ndim` : Number of dimensions
- `shape` : Size of each dimension
- `size` : Total number of elements
- `dtype` : Data type

**Predict first:** for the array `arr` from Part 2, what do you *expect* `ndim`, `shape`, `size`, and `dtype` to be? Write your guess below before running the next cell.

*Your prediction:*


In [5]:
arr.ndim, arr.shape, arr.size, arr.dtype


(1, (5,), 5, dtype('int64'))

### Observation

Was your prediction correct? If not, what did you get wrong and why?

Dimension:  My prediction was correct. The dimension is 1 because arr is a one-dimensional array. #AP24110010828

Shape:  The size is 5 because there are 5 total elements in the array.

Size:  The size is 5 because there are 5 total elements in the array. #AP24110010828

Data Type:  The data type is an integer type because all the values in the array are whole numbers. #AP24110010828


## Part 4: Special Arrays

These are commonly used to initialize data — for example, `zeros` is often used to create an empty "canvas" array before filling in real values (you'll see this again in the image section).


In [6]:
np.zeros((3,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((4,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Student Practice

Create a `5x5` array of all zeros, and a `2x6` array of all ones. Write both below.


In [9]:

zeros_array = np.zeros((5, 5))

# Display the zero array.
print("5 x 5 Zero Array:")   #AP24110010828
print(zeros_array)

# Create a 2 by 6 array containing only ones.
ones_array = np.ones((2, 6))     #AP24110010828

# Display the one array.
print("\n2 x 6 Ones Array:")    #AP24110010828
print(ones_array)


5 x 5 Zero Array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

2 x 6 Ones Array:
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


## Part 5: Sequence Generation

In [10]:
np.arange(0,50,5)


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [11]:
np.linspace(0,100,10)


array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

### Student Practice

`np.arange` and `np.linspace` both generate sequences but work differently.

1. Use `np.arange` to generate even numbers from 2 to 20.
2. Use `np.linspace` to generate 5 evenly spaced numbers between 0 and 1.
3. In one sentence, write the difference between `arange` (step-based) and `linspace` (count-based).


In [12]:
# Generate even numbers starting at 2 and stopping before 22.
# The step size is 2.
even_numbers = np.arange(2, 22, 2)                          #AP24110010828

# Display the even numbers.
print("Even numbers:", even_numbers)                         #AP24110010828

# Generate 5 equally spaced values from 0 to 1.
# The third argument specifies that we want 5 values.
evenly_spaced = np.linspace(0, 1, 5)

# Display the equally spaced values.
print("Evenly spaced numbers:", evenly_spaced)               #AP24110010828


Even numbers: [ 2  4  6  8 10 12 14 16 18 20]
Evenly spaced numbers: [0.   0.25 0.5  0.75 1.  ]


## Part 6: Random Numbers

In [13]:
np.random.rand(5)


array([0.6349285 , 0.5201935 , 0.57190484, 0.92251514, 0.49777127])

In [14]:
np.random.randint(1,100,10)


array([40, 90, 78, 78,  3, 91, 43, 67, 63, 33])

In [15]:
# Generate 5 random floating-point numbers between 0 and 1.
random_values = np.random.rand(5)                         #AP24110010828

# Display the random values.
print(random_values)                                      #AP24110010828

# Generate 10 random integers from 1 up to, but not including, 100.
random_integers = np.random.randint(1, 100, 10)

# Display the random integers.
print(random_integers)                                    #AP24110010828

[4.28390800e-01 7.25293884e-01 8.58627215e-01 9.90919371e-01
 1.79166515e-04]
[50 30 94 66 73 29 49 92 61 14]


## Part 7: Reshaping Arrays

Reshape changes the *structure* of an array without changing the data.

**Rule: the total number of elements must stay the same.** `3x4 = 12` elements, so you can reshape into any combination of dimensions that multiplies to 12 (e.g. `2x6`, `4x3`, `1x12`, `12x1`).


In [16]:
a = np.arange(12)
a.reshape(3,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Student Practice — valid shapes

Try reshaping `a` into these shapes. Write each as a separate line:
- 2 x 6
- 4 x 3
- 6 x 2


In [17]:
# Import NumPy.
import numpy as np

# Create an array containing 12 numbers.
a = np.arange(12)                                   #AP24110010828

# Reshape the array into 2 rows and 6 columns.
array_2x6 = a.reshape(2, 6)                          #AP24110010828

# Display the result.
print(array_2x6)                                     #AP24110010828

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [18]:
# Import NumPy.
import numpy as np

# Create an array containing 12 numbers.
a = np.arange(12)                                   #AP24110010828

# Reshape the array into 4 rows and 3 columns.
array_4x3 = a.reshape(4, 3)                         #AP24110010828

# Display the result.
print(array_4x3)                                    #AP24110010828

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [19]:
# Import NumPy.
import numpy as np

# Create an array containing 12 numbers.
a = np.arange(12)                                         #AP24110010828

# Reshape the array into 6 rows and 2 columns.
array_6x2 = a.reshape(6, 2)                               #AP24110010828

# Display the result.
print(array_6x2)                                           #AP24110010828

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


### Student Practice — break it on purpose

Now try `a.reshape(5,3)`. This should throw an error because 5 × 3 = 15 ≠ 12.

Run it, read the error message, then answer: **why did it fail, and what rule does it confirm about reshape?**

*Your answer:*


In [20]:
# Import NumPy.
import numpy as np

# Create an array containing 12 elements.
a = np.arange(12)n                                      #AP24110010828

# Display the original array.
print("Original array:")
print(a)                                                #AP24110010828

# Try to reshape the 12 elements into 5 rows and 3 columns.
# This produces a ValueError because 5 × 3 = 15,
# but the array contains only 12 elements.
a.reshape(5, 3)                                         #AP24110010828

SyntaxError: invalid syntax (2203542579.py, line 5)

it fails because the original array contains 12 elements, but a 5 × 3 array would require 15 elements.

Rule: The total number of elements must remain unchanged when reshaping.

## Part 8: Indexing and Slicing

In [ ]:
matrix = np.arange(1,10).reshape(3,3)
matrix


In [ ]:
# Extract first row
matrix[0]


In [ ]:
# Extract first column
matrix[:,0]


### Student Practice

Using `matrix` above, write code to extract:
1. The last row
2. The last column
3. The single element in the middle (row 1, column 1)
4. The bottom-right 2x2 sub-matrix


In [ ]:

# Import NumPy.
import numpy as np
                                                             #AP24110010828
# Create a 3x3 matrix containing numbers from 1 to 9.
matrix = np.arange(1, 10).reshape(3, 3)

# Display the original matrix.
print("Matrix:")
print(matrix)

# Extract the last row.
last_row = matrix[-1]

# Display the last row.
print("Last row:", last_row)

# Extract the last column.
last_column = matrix[:, -1]

# Display the last column.                             #AP24110010828
print("Last column:", last_column)

# Extract the middle element.
middle_element = matrix[1, 1]

# Display the middle element.
print("Middle element:", middle_element)

# Extract the bottom-right 2x2 matrix.                  #AP24110010828
bottom_right = matrix[1:3, 1:3]

# Display the bottom-right 2x2 matrix.
print("Bottom-right 2x2 matrix:")
print(bottom_right)

## Part 9: Mathematical Operations

In [ ]:
marks = np.array([60,70,80,90])

marks + 5


In [ ]:
marks * 2


### Student Practice

A student scored `marks = [55, 62, 48, 91, 73]` but every question was later found to be worth 1 extra bonus mark, and then the whole test was scaled to be out of 150 (currently out of 100, so multiply by 1.5).

Write the NumPy code to: (1) add the bonus mark to every score, then (2) scale to out of 150.


In [ ]:
# Create the original marks array.
marks = np.array([55, 62, 48, 91, 73])                    #AP24110010828

# Add one bonus mark to every student's score.
bonus_marks = marks + 1

# Multiply every score by 1.5 to scale it to 150.
scaled_marks = bonus_marks * 1.5
                                                         #AP24110010828
# Display the original marks.
print("Original marks:", marks)

# Display the marks after adding the bonus.
print("After bonus:", bonus_marks)

# Display the final scaled marks.                      #AP24110010828
print("Scaled marks:", scaled_marks)


## Part 10: Broadcasting

Broadcasting lets NumPy perform operations between arrays of **different shapes**, without writing an explicit loop, by "stretching" the smaller array to match the larger one — as long as their shapes are compatible.

**The basic rule:** starting from the trailing (rightmost) dimension, two dimensions are compatible if they're equal, or one of them is 1. NumPy then virtually repeats the size-1 dimension to match.

You already used broadcasting in Part 9 (`marks + 5`) — a single number (shape `()`) was broadcast across the whole array. Here's a less obvious example: a 1D array broadcast across a 2D array.


In [ ]:
salary = np.array([30000,40000,50000])

salary * 1.10


In [ ]:
# A less obvious broadcasting example: adding a 1D array to every row of a 2D array
grid = np.ones((3,3))       # shape (3,3)
row_bonus = np.array([1,2,3])  # shape (3,)

grid + row_bonus


### Student Practice — predict then check

Before running the next cell, predict the output shape and values on paper.

`np.array([[1],[2],[3]]) + np.array([10,20,30])`

(Hint: one array has shape `(3,1)`, the other `(3,)`. Think about how each dimension aligns.)

*Your prediction:*


In [ ]:
# Run this after writing your prediction above, and compare
np.array([[1],[2],[3]]) + np.array([10,20,30])          #AP24110010828


# Create a column vector with shape (3, 1).
a = np.array([[1], [2], [3]])

# Create a one-dimensional array with shape (3,).     #AP24110010828
b = np.array([10, 20, 30])

# Add the arrays.
# NumPy broadcasts the arrays to compatible shapes.  #AP24110010828
result = a + b

# Display the result.
print(result)


# **Reflection:** In your own words, explain broadcasting with an example of your own (not one from this notebook).

*Your answer:*Broadcasting allows NumPy to perform calculations between arrays with compatible shapes without explicitly writing loops. For example, if we have temperatures for three cities and want to add 2 degrees to every temperature, we can simply add 2 to the array. NumPy automatically applies the value to every element.


## Part 11: Filtering Data (Boolean Indexing)

In [ ]:
marks = np.array([45,67,89,32,90,55])

marks[marks > 60]


### Student Practice

Using the `marks` array above:
1. Extract all marks that are failing (below 40).
2. Count how many students scored above 80 (hint: `.sum()` on a boolean array counts `True` values).
3. Replace all failing marks with 0 using `np.where`.


In [ ]:
# Create the marks array.
marks = np.array([45, 67, 89, 32, 90, 55])        #AP24110010828

# Select all marks below 40.
failing_marks = marks[marks < 40]

# Display the failing marks.
print("Failing marks:", failing_marks)

# Check which marks are greater than 80.
# The comparison produces True or False values.
above_80 = marks > 80

# Sum the True values to count how many students scored above 80.#AP24110010828
count_above_80 = above_80.sum()

# Display the number of students above 80.
print("Students above 80:", count_above_80)

# Replace marks below 40 with 0.
# np.where chooses 0 when the condition is True,    #AP24110010828
# otherwise it keeps the original mark.
updated_marks = np.where(marks < 40, 0, marks)

# Display the updated marks.
print("Updated marks:", updated_marks)


## Part 12: Joining Arrays

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])

np.concatenate([a,b])


In [ ]:
# Create the first array.
a = np.array([1, 2, 3])         #AP24110010828

# Create the second array.
b = np.array([4, 5, 6])

# Join both arrays into one array.#AP24110010828
combined = np.concatenate([a, b])

# Display the combined array.#AP24110010828
print(combined)

## Part 13: Splitting Arrays

In [ ]:
x=np.arange(12)

np.split(x,3)


### Student Practice

1. Split `x` into 4 equal parts instead of 3.
2. Try `np.split(x, 5)` — this should fail. Read the error and explain in one sentence why splitting into 5 doesn't work for 12 elements.


In [ ]:
# Create an array containing 12 values.#AP24110010828
x = np.arange(12)

# Split the 12 values into 4 equal arrays.
four_parts = np.split(x, 4)

# Display the four parts. #AP24110010828
print("Four equal parts:")
print(four_parts)
#AP24110010828

# Part 14: Image Analysis Using NumPy

## Why this matters for ML

A digital image **is** a NumPy array — this is exactly the data format used to feed images into computer vision models (e.g. CNNs). Every preprocessing step you do below (resizing, cropping, normalizing pixel values, flipping for data augmentation) is a real step used in production ML image pipelines, not just a classroom exercise.

## Image Shape Guidelines

A colour image is represented as:

`(height, width, channels)`

Example: `512 x 512 x 3` means:
- Height = 512 pixels
- Width = 512 pixels
- RGB colour channels = 3

**Avoid very large images** — a `4000 x 4000 x 3` image has 48 million individual pixel values. That's a lot to process and display.

Recommended:
- Practice: 300x300 pixels
- Processing: 512x512 pixels


In [ ]:
from google.colab import files

uploaded = files.upload()


In [ ]:
# The 'uploaded' variable is a dictionary: {filename: file_bytes}
# This line grabs the filename automatically instead of you typing it by hand
image_filename = list(uploaded.keys())[0]
print("Uploaded file:", image_filename)


> **Note:** the cell above only works in Google Colab. If you're running this notebook locally (Jupyter/VS Code), skip it and instead set `image_path = "your_local_file.jpg"` directly in the next cell.

Upload an image file and note its name below:

Image name:


In [ ]:
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

# TASK: Load your uploaded image and convert it to a NumPy array.
# 1. Open the image with PIL: Image.open(image_filename)
# 2. Convert it to a NumPy array with np.array(...)
# 3. Print its .shape

img_array = None  # replace this line with your code


## Image Display

**Do not print the complete image array** (it's thousands of numbers and unreadable). Instead:
- Use `image.shape` to check dimensions
- Use `plt.imshow(...)` to *see* the image visually

### Student Practice
Display your uploaded image using `plt.imshow()` and turn off the axis with `plt.axis("off")`.


In [ ]:
#AP24110010828
from google.colab import files
from PIL import Image
import matplotlib.pyplot as plt

uploaded = files.upload()

filename = list(uploaded.keys())[0] #AP24110010828

image = Image.open(filename)

print("Image size:", image.size)
print("Image mode:", image.mode) #AP24110010828

plt.imshow(image)
plt.axis("off")
plt.show()


## Image Cropping

### Student Practice
Crop the **center 200x200 region** of your image (not a random corner — think about how to calculate the center offset from `img_array.shape`), store it in a variable called `crop`, and display it.


In [ ]:
# AP24110010828

# Import the image upload function.
from google.colab import files

# Import PIL.
from PIL import Image

# Import NumPy.
import numpy as np

# Upload the image.
uploaded = files.upload()
#AP24110010828
# Get the uploaded file name.
filename = list(uploaded.keys())[0]

# Open the image and convert it to RGB.
image = Image.open(filename).convert("RGB")

# Convert the image into a NumPy array.
img_array = np.array(image)#AP24110010828

# Display the image shape.
print("Image shape:", img_array.shape)

### Quick demo: showing multiple images side by side

You'll want to display more than one image at once in the tasks below (e.g. two flipped versions, or three RGB channels). `plt.subplots()` lets you do this in a grid. Study this small example, then reuse the pattern.


In [ ]:
# Demo: showing 2 plots side by side using plt.subplots
fig, axes = plt.subplots(1, 2, figsize=(8,4))

axes[0].imshow(img_array)
axes[0].set_title("Original")
axes[0].axis("off")

axes[1].imshow(img_array)
axes[1].set_title("Original (again, just for demo)")
axes[1].axis("off")

plt.show()


## Image Flipping

### Student Practice
Produce and display both a vertical flip and a horizontal flip of your image using slicing (`[::-1]`), without using any built-in flip function.


In [ ]:
# AP24110010828

# Import NumPy
import numpy as np

# Import Matplotlib for displaying the images AP24110010828
import matplotlib.pyplot as plt

# Flip the image vertically (top becomes bottom)AP24110010828
vertical_flip = np.flipud(img_array)

# Flip the image horizontally (left becomes right)AP24110010828
horizontal_flip = np.fliplr(img_array)

# Display the original image
plt.figure(figsize=(5, 5))
plt.imshow(img_array)
plt.title("Original Image")
plt.axis("off")
plt.show()

# Display the vertically flipped image
plt.figure(figsize=(5, 5))
plt.imshow(vertical_flip)
plt.title("Vertical Flip")
plt.axis("off")
plt.show()

# Display the horizontally flipped image
plt.figure(figsize=(5, 5))
plt.imshow(horizontal_flip)
plt.title("Horizontal Flip")
plt.axis("off")
plt.show()

## RGB Channel Analysis

RGB channels:

- 0 - Red
- 1 - Green
- 2 - Blue

### Student Practice
Extract the red, green, and blue channels separately, and display each one using `plt.imshow(channel, cmap="gray")` so you can see which areas of the image are strongest in each color.


In [ ]:
# Extract the red channel.
red_channel = img_array[:, :, 0]

# Extract the green channel.
green_channel = img_array[:, :, 1]#AP24110010828

# Extract the blue channel.
blue_channel = img_array[:, :, 2]

# Create three side-by-side plots.
fig, axes = plt.subplots(1, 3, figsize=(12, 4))

# Display the red channel.
axes[0].imshow(red_channel, cmap="gray")
axes[0].set_title("Red Channel")#AP24110010828
axes[0].axis("off")

# Display the green channel.
axes[1].imshow(green_channel, cmap="gray")
axes[1].set_title("Green Channel")
axes[1].axis("off")

# Display the blue channel.#AP24110010828
axes[2].imshow(blue_channel, cmap="gray")
axes[2].set_title("Blue Channel")
axes[2].axis("off")

# Display all three channels.
plt.show()

## Brightness Analysis

### Student Practice
Calculate the average brightness of your image using `np.mean()`. Then calculate the average brightness of just the red channel, just the green channel, and just the blue channel. Which channel is brightest? Write your answer below the code.


In [ ]:
# Calculate the average pixel value of the complete image.
average_brightness = np.mean(img_array)

# Calculate the average value of the red channel.#AP24110010828
red_brightness = np.mean(red_channel)

# Calculate the average value of the green channel.
green_brightness = np.mean(green_channel)

# Calculate the average value of the blue channel.#AP2411001828
blue_brightness = np.mean(blue_channel)

# Print the overall average brightness.
print("Overall brightness:", average_brightness)

# Print the red-channel brightness.
print("Red brightness:", red_brightness)#AP24110010828

# Print the green-channel brightness.
print("Green brightness:", green_brightness)

# Print the blue-channel brightness.#AP24110010828
print("Blue brightness:", blue_brightness)


*Your answer:*The overall brightness represents the average pixel value of the complete image. The red, green, and blue brightness values show the average intensity of each colour channel. Comparing these values helps us understand which colour contributes more to the brightness of the chanels.


## Thresholding

Convert the image into pure black-and-white using `np.where()`.

### Student Practice
1. Convert the image to grayscale by averaging the 3 channels (`axis=2`).
2. Use `np.where(gray > 128, 255, 0)` to create a binary (black/white) version.
3. Display the result.
4. Try a different threshold (e.g. 100 or 180) and observe how it changes the result.


In [ ]:
# Import NumPy.
import numpy as np

# Import Matplotlib.
import matplotlib.pyplot as plt#AP24110010828

# Import Image from PIL.
from PIL import Image

# Import the file upload tool for Google Colab.
from google.colab import files

# Upload the teddy bear image.
uploaded = files.upload()

# Get the name of the uploaded image.#AP24110010828
filename = next(iter(uploaded))

# Open the teddy bear image.
image = Image.open(filename)

# Convert the image to RGB.
# This makes sure the image has exactly 3 colour channels.
image = image.convert("RGB")

# Convert the image into a NumPy array.#AP24110010828
img_array = np.array(image)

# Calculate the average of the Red, Green, and Blue channels.
# axis=2 means that the three colour channels are averaged.
gray = np.mean(img_array, axis=2)

# Convert the grayscale image into black and white.
# Pixels greater than 128 become 255 (white).#AP24110010828
# Pixels less than or equal to 128 become 0 (black).
binary = np.where(gray > 128, 255, 0)

# Display the thresholded black-and-white image.
plt.imshow(binary, cmap="gray")
#AP24110010828
# Hide the x-axis and y-axis.
plt.axis("off")

# Display the result.
plt.show()

# Mini Project: Image Analyzer

Write a single program (you can reuse code from above) that prints/displays all of the following for your uploaded image, in order:

1. Image height, width, and number of channels
2. Average brightness (overall, and per channel)
3. The cropped center region
4. Both flipped versions (vertical and horizontal)
5. All 3 RGB channels shown separately
6. The thresholded (black/white) version

### Self-check before you submit
- [ ] I wrote the code myself rather than only uncommenting given code
- [ ] I can explain what every line does, not just that it runs
- [ ] My image display uses `plt.axis("off")` and looks correct
- [ ] I answered all reflection questions in my own words

## Reflection Questions

1. Why is NumPy faster than Python lists? (Refer back to your Part 1 answer — refine it if needed.)

2. Explain broadcasting with an example of your own.

3. What does image shape `(512,512,3)` represent?

4. Why should we avoid printing complete image arrays?

5. Explain RGB channels.

6. Where might you use this exact image-array workflow in a real machine learning project (e.g. what comes right before feeding an image into a CNN)?


# Part 15: Text Analysis Using NumPy (NLP Track)

## Why this matters for ML/NLP

Before any NLP model (sentiment classifier, spam detector, chatbot) can process text, the text must be converted into numbers — this is called **vectorization**. NumPy arrays are the underlying data structure for almost every text representation: word counts, one-hot vectors, TF-IDF vectors, and even word embeddings are all just NumPy (or NumPy-like) arrays.

In this section, you'll build a small text analysis pipeline entirely with NumPy — no external NLP libraries — so you understand what's actually happening under the hood before you use libraries like `scikit-learn` or `nltk` later in the course.


## Step 1: From Text to Tokens

The first step in any NLP pipeline is **tokenization** — splitting text into individual words.

### Demonstration


In [ ]:
sentence = "NumPy makes numerical computing fast and NumPy makes arrays powerful"

# Basic tokenization: lowercase + split on spaces
tokens = sentence.lower().split()
print(tokens)


### Student Practice

Tokenize this sentence the same way: `"Data Science and Machine Learning use NumPy arrays every single day"`. Store the result in a variable called `tokens2`.


In [ ]:
# Store the sentence in a string. #AP24110010828
sentence2 = "Data Science and Machine Learning use NumPy arrays every single day"

# Convert all letters to lowercase and split the sentence into words.
tokens2 = sentence2.lower().split() #AP24110010828

# Display the individual words.
print(tokens2)  #AP24110010828


## Step 2: Building a Vocabulary

A **vocabulary** is the set of all unique words across your text(s). We'll use `np.unique()` — the same function idea you used earlier for arrays of numbers, now applied to an array of words.


In [ ]:
tokens_array = np.array(tokens)
vocabulary = np.unique(tokens_array)
print("Vocabulary:", vocabulary)
print("Vocabulary size:", len(vocabulary))


### Student Practice

Build the vocabulary for `tokens2` from Step 1. How many unique words does it contain?


In [ ]:
# Write your answer here
# Convert the list of tokens into a NumPy array.
tokens2_array = np.array(tokens2)      #AP24110010828

# Find all unique words and sort them.
vocabulary2 = np.unique(tokens2_array)

# Display the vocabulary.
print("Vocabulary:", vocabulary2)    #AP24110010828

# Count the number of unique words.
vocabulary_size = len(vocabulary2)

# Display the vocabulary size. #AP24110010828
print("Vocabulary size:", vocabulary_size)

There are 11 unique words, because no word is repeated in the sentence.

## Step 3: Word Frequency Vector (Bag-of-Words)

A **bag-of-words** vector represents a sentence as an array of word counts, one count per vocabulary word — this ignores word order but captures *what* words appear and *how often*.

### Demonstration: build a word-count vector by hand using NumPy


In [ ]:
def bag_of_words_vector(tokens, vocabulary):
    # For each word in the vocabulary, count how many times it appears in tokens
    vector = np.array([np.sum(np.array(tokens) == word) for word in vocabulary])
    return vector

vec = bag_of_words_vector(tokens, vocabulary)
print(vocabulary)
print(vec)


### Student Practice — predict then check

Before running, predict: which word(s) will have a count of 2 in the vector above? (Hint: look back at the original sentence — which word repeats?)

*Your prediction:*

Now build the bag-of-words vector for `tokens2` using its own vocabulary, and check your prediction concept applies the same way.


In [ ]:
# Write your answer here
# Define a function for creating a bag-of-words vector.
def bag_of_words_vector(tokens, vocabulary):

    # Convert the tokens into a NumPy array.
    token_array = np.array(tokens)     #AP24110010828

    # Count how many times each vocabulary word appears.
    vector = np.array([
        np.sum(token_array == word)
        for word in vocabulary
    ])

    # Return the completed count vector.
    return vector


# Create the bag-of-words vector for tokens2.#AP24110010828
vec2 = bag_of_words_vector(tokens2, vocabulary2)

# Display the vocabulary.
print("Vocabulary:", vocabulary2) #AP24110010828

# Display the corresponding word-count vector.
print("Bag-of-words vector:", vec2)

In [ ]:
# Build the vocabulary for tokens2.
vocabulary2 = np.unique(np.array(tokens2))  #AP24110010828

# Create the bag-of-words vector.
vec2 = bag_of_words_vector(tokens2, vocabulary2)

# Print the vocabulary.
print("Vocabulary:", vocabulary2)
#AP24110010828
# Print the vector.
print("Vector:", vec2)#AP24110828

Since every word occurs exactly once, every value in the vector is 1.

## Step 4: Comparing Two Sentences (Cosine Similarity)

Once text is turned into number vectors, we can measure how *similar* two sentences are using **cosine similarity** — a formula you'll see constantly in NLP and recommendation systems:

$$\text{cosine similarity} = \frac{A \cdot B}{\|A\| \times \|B\|}$$

This measures the angle between two vectors, not their length — so it works even if one sentence is longer than another.

### Demonstration


In [ ]:
sentence_a = "machine learning uses numpy arrays"
sentence_b = "deep learning also uses numpy arrays heavily"

tokens_a = sentence_a.lower().split()
tokens_b = sentence_b.lower().split()

# Build a shared vocabulary from both sentences combined
combined_vocab = np.unique(np.array(tokens_a + tokens_b))

vec_a = bag_of_words_vector(tokens_a, combined_vocab)
vec_b = bag_of_words_vector(tokens_b, combined_vocab)

print("Vector A:", vec_a)
print("Vector B:", vec_b)

# Cosine similarity using NumPy dot product and norm
cosine_sim = np.dot(vec_a, vec_b) / (np.linalg.norm(vec_a) * np.linalg.norm(vec_b))
print("Cosine similarity:", cosine_sim)


### Student Practice

Pick two sentences of your own (write them below) — one pair that should be *similar* in meaning/topic, and one pair that should be *very different*. Compute the cosine similarity for both pairs and confirm your intuition matches the numbers.


In [ ]:
# Write your answer here
# Create the first pair of similar sentences.
similar_a = "I enjoy machine learning"
similar_b = "I like machine learning"

# Convert the first sentence into lowercase tokens.#AP24110010828
tokens_a = similar_a.lower().split()

# Convert the second sentence into lowercase tokens.
tokens_b = similar_b.lower().split() #AP24110010828

# Create one vocabulary containing words from both sentences.
shared_vocab = np.unique(np.array(tokens_a + tokens_b))

# Convert the first sentence into a bag-of-words vector.
vector_a = bag_of_words_vector(tokens_a, shared_vocab)

# Convert the second sentence into a bag-of-words vector.
vector_b = bag_of_words_vector(tokens_b, shared_vocab)
#AP24110010828
# Calculate cosine similarity using the dot product.
similarity = np.dot(vector_a, vector_b)

# Divide by the product of the vector lengths.
similarity = similarity / (
    np.linalg.norm(vector_a) * np.linalg.norm(vector_b)
)

# Display the similarity score.
print("Similarity score:", similarity)

**Reflection:** In your own words, why does cosine similarity give a value close to 1 for similar sentences and close to 0 for unrelated sentences? What would a `cosine similarity` of exactly 1 mean about two vectors?

*Your answer:* Cosine similarity measures the angle between two vectors. If two sentences contain many of the same words, their vectors point in similar directions, so their cosine similarity is closer to 1. If they have very few words in common, their vectors point in different directions, so the similarity is closer to 0.

A cosine similarity of exactly 1 means that the two non-zero vectors point in exactly the same direction. They have the same pattern of values, even if their magnitudes are different.


## Step 5: Most Frequent Words

### Student Practice

Take any paragraph of your choice (3-4 sentences, write it below as a string). Then:
1. Tokenize it.
2. Build its vocabulary and word-count vector (reuse `bag_of_words_vector`).
3. Use NumPy to find and print the **top 3 most frequent words** (hint: look at sorting — `np.argsort()` sorts indices by value, and slicing with `[::-1]` reverses order).


In [ ]:
# Write your answer here
# Create a paragraph containing four sentences.
paragraph = """
NumPy is useful for numerical computing.
NumPy provides efficient array operations.
Python programs use NumPy for data analysis.
Data analysis becomes easier with NumPy arrays.
"""

# Convert the paragraph to lowercase and split it into words.
tokens = paragraph.lower().split() #AP24110010828

# Create a NumPy array containing all tokens.
tokens_array = np.array(tokens)

# Find all unique words.  #AP24110010828
vocabulary = np.unique(tokens_array)

# Create a bag-of-words count vector.
word_counts = bag_of_words_vector(tokens, vocabulary)

# Sort the indices according to word frequency.
sorted_indices = np.argsort(word_counts) #AP24110010828

# Reverse the indices so that the most frequent words come first.
top_indices = sorted_indices[::-1]

# Select the first three indices.
top_three_indices = top_indices[:3]

# Get the three most frequent words.
top_words = vocabulary[top_three_indices]

# Get their corresponding counts.
top_counts = word_counts[top_three_indices]

# Print the top three words and their frequencies.
for word, count in zip(top_words, top_counts):

    # Display the word and its frequency.
    print(word, ":", count)

# Mini Project: Simple Text Similarity Checker (NLP Track)

Build a small program that:

1. Takes **three** short sentences of your choice (write them as strings).
2. Tokenizes all three and builds one shared vocabulary across all of them.
3. Converts each sentence into a bag-of-words vector using that shared vocabulary.
4. Computes cosine similarity between every pair of sentences (3 pairs total: 1-2, 1-3, 2-3).
5. Prints which two sentences are the **most similar** to each other, based on the highest cosine similarity score.

### Self-check before you submit
- [ ] I wrote my own three sentences (not copied from the notebook)
- [ ] I can explain what a bag-of-words vector represents, in my own words
- [ ] I can explain why cosine similarity works even when sentences are different lengths
- [ ] My program correctly identifies and prints the most similar pair

## Reflection Questions (NLP Track)

1. Why do we need to convert text into numbers before a machine learning model can use it?


ANS:  Machine-learning algorithms work with numerical data rather than raw text strings. Therefore, words must be converted into numerical representations such as word counts, TF-IDF vectors, or embeddings so that mathematical operations can be performed on them   
#AP24110010828




2. What information does a bag-of-words vector *lose* about the original sentence? (Hint: think about what `split()` and counting alone doesn't capture.)


ANS:A bag-of-words representation loses word order and grammatical structure. For example, "dog bites man" and "man bites dog" contain the same words and could produce the same word-count vector even though their meanings are different.
#AP24110010828



3. Why might cosine similarity be a better similarity measure than simply comparing raw word-count differences?
#AP24110010828

ANS:Cosine similarity compares the direction of vectors rather than simply comparing their numerical sizes. This makes it useful when sentences have different lengths. Two documents can have different numbers of words but still have similar word distributions.




4. Name one real-world application that likely uses something like this text-vectorization + similarity approach (e.g. search engines, plagiarism checkers, recommendation systems — pick one and explain briefly).
#AP24110010828

ANS:Search engines can use text-vectorization and similarity techniques to compare a user's search query with documents. The query and documents can be converted into numerical vectors, and similarity scores can help determine which documents are most relevant to the search.


In [ ]:
# Create three sentences.
sentence1 = "I like machine learning"
sentence2 = "I enjoy machine learning"
sentence3 = "I love playing football"

# Tokenize the first sentence.
tokens1 = sentence1.lower().split()

# Tokenize the second sentence.
tokens2 = sentence2.lower().split()

# Tokenize the third sentence.
tokens3 = sentence3.lower().split()

# Combine all tokens from the three sentences.
all_tokens = tokens1 + tokens2 + tokens3

# Create one shared vocabulary for all three sentences.
shared_vocab = np.unique(np.array(all_tokens))

# Convert sentence 1 into a bag-of-words vector.
vector1 = bag_of_words_vector(tokens1, shared_vocab)

# Convert sentence 2 into a bag-of-words vector.
vector2 = bag_of_words_vector(tokens2, shared_vocab)

# Convert sentence 3 into a bag-of-words vector.
vector3 = bag_of_words_vector(tokens3, shared_vocab)


# Define a function for cosine similarity.
def cosine_similarity(vector_a, vector_b):

    # Calculate the dot product of the two vectors.
    dot_product = np.dot(vector_a, vector_b)

    # Calculate the length of the first vector.
    norm_a = np.linalg.norm(vector_a)

    # Calculate the length of the second vector.
    norm_b = np.linalg.norm(vector_b)

    # Return the cosine similarity.
    return dot_product / (norm_a * norm_b)

#AP24110010828
# Calculate similarity between sentence 1 and sentence 2.
similarity_12 = cosine_similarity(vector1, vector2)

# Calculate similarity between sentence 1 and sentence 3.
similarity_13 = cosine_similarity(vector1, vector3)

# Calculate similarity between sentence 2 and sentence 3.
similarity_23 = cosine_similarity(vector2, vector3)   #AP24110010828

# Print all three similarity scores.
print("Sentence 1 vs Sentence 2:", similarity_12)
print("Sentence 1 vs Sentence 3:", similarity_13)
print("Sentence 2 vs Sentence 3:", similarity_23)


# Store the three similarity scores in an array.#AP24110010828
similarities = np.array([
    similarity_12,
    similarity_13,
    similarity_23
])

# Find the index of the largest similarity score.
best_index = np.argmax(similarities)

# Store the names of the three sentence pairs. #AP24110010828
pairs = [
    "Sentence 1 and Sentence 2",
    "Sentence 1 and Sentence 3",
    "Sentence 2 and Sentence 3"
]

# Print the most similar pair.
print("Most similar pair:", pairs[best_index])

# Print the highest similarity score.
print("Highest similarity:", similarities[best_index])